services:
  configs-service:
    build: ./
    container_name: configs-service
    healthcheck:
      test: [ "CMD", 'sh', '-c', 'echo -e "Checking service availability"; while ! nc -z "discovery-service" 4080; do sleep 1; printf "-"; done; echo -e " >> Service has started";' ]
      timeout: 10s
      retries: 10
    ports:
      - "8888:8888"
    expose:
      - "8888"
    networks:
      - fcNet
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=${SPRING_CONFIG_IMPORT}
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
      - OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
      - OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER}
      - OTEL_METRIC_EXPORT_INTERVAL=${OTEL_METRIC_EXPORT_INTERVAL}
      - TZ=${TIMEZONE}
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}

networks:
  fcNet:
    name: fcNet
    external: true
    driver: bridge