services:
  configs-service:
    image: ${ECR_REPOSITORY}/configs-service:latest
    container_name: configs-service
    healthcheck:
      test: [ "CMD", 'sh', '-c', 'echo -e "Checking service availability"; while ! nc -z "configs-service" 8888; do sleep 1; printf "-"; done; echo -e " >> Service has started";' ]
      timeout: 10s
      retries: 10
    ports:
      - "8888:8888"
    expose:
      - "8888"
    networks:
      - fcNet
      - jaegerNet
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
      - OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
      - OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER}
      - OTEL_METRIC_EXPORT_INTERVAL=${OTEL_METRIC_EXPORT_INTERVAL}
      - TZ=${TIMEZONE}

networks:
  fcNet:
    name: fcNet
    external: true
    driver: bridge
  jaegerNet:
    name: jaegerNet
    external: true
    driver: bridge